version: 2

jobs:
  test:
    working_directory: ~/webreview
    docker:
    - image: ubuntu:xenial
    steps:
    - checkout

    - run:
        name: Update Pip
        command: |
          apt-get update
          apt-get install -y --no-install-recommends \
            python3 python3-pip python3-setuptools python3-all-dev python3-dev

    - run:
        name: Install and run pipenv
        command: |
          pip3 install --upgrade wheel
          pip3 install --upgrade pip virtualenv pipenv
          pipenv install --dev

    - run:
        name: Client Secret
        command: |
          echo $CLIENT_SECRET | base64 --decode > ~/client-secret.json

    - run:
        name: Run Tests
        command: |
          pipenv run nosetests \
            -v \
            --rednose \
            --with-coverage \
            --cover-erase \
            --cover-xml \
            --cover-package=webreview \
            webreview
        environment:
          AUTH_KEY_FILE: ~/client-secret.json

workflows:
  version: 2
  test:
    jobs:
    - test
